const { app, BrowserWindow, Menu } = require('electron');
const path = require('path');
const isDev = process.env.NODE_ENV === 'development';

function createWindow() {
    // Set the Menu to null to hide default menu bar
    Menu.setApplicationMenu(null);

    const win = new BrowserWindow({
        width: 1400,
        height: 900,
        backgroundColor: '#020617', // Match slate-950
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
        },
        title: 'PTS Software Suite'
    });

    if (isDev) {
        win.loadURL('http://localhost:3000');
    } else {
        // Load the static export generated by 'next build'
        win.loadFile(path.join(__dirname, '../out/index.html'));
    }
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});
